import React, { useState, useEffect } from 'react';

const API_URL = import.meta.env.VITE_API_URL || (typeof window !== 'undefined' && window.location.hostname === 'localhost' && window.location.port !== '5000' ? 'http://localhost:5000' : '');

const DEFAULT_PROFILE = {
  clinic_name: '',
  tagline: '',
  address: '',
  city: '',
  country: '',
  phone: '',
  email: '',
  website: '',
  reg_number: '',
  footer_note: '',
  disclaimer: '',
  logo: ''
};

export default function ClinicProfile() {
  const [profile, setProfile] = useState(DEFAULT_PROFILE);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    fetch(`${API_URL}/api/clinic-profile`)
      .then(r => r.json())
      .then(data => { setProfile(data); setLoading(false); })
      .catch(() => setLoading(false));
  }, []);

  const handleChange = (field, value) => {
    setProfile(prev => ({ ...prev, [field]: value }));
    setSaved(false);
  };

  const handleLogoUpload = (e) => {
    const file = e.target.files[0];
    if (!file) return;

    if (file.size > 512000) {
      if (window.showToast) window.showToast('Logo image must be smaller than 500KB.', 'warning');
      return;
    }

    const reader = new FileReader();
    reader.onload = (uploadEvent) => {
      handleChange('logo', uploadEvent.target.result);
    };
    reader.readAsDataURL(file);
  };

  const handleSave = async () => {
    if (!profile.clinic_name || !profile.phone) {
      if (window.showToast) window.showToast('Clinic name and phone number are required.', 'warning');
      return;
    }
    setSaving(true);
    try {
      const res = await fetch(`${API_URL}/api/clinic-profile`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(profile)
      });
      if (res.ok) {
        const updated = await res.json();
        setProfile(updated);
        setSaved(true);
        if (window.showToast) window.showToast('Clinic profile saved successfully!', 'success');
        // Notify other components to refresh clinic profile
        window.dispatchEvent(new CustomEvent('clinic-profile-updated', { detail: updated }));
      } else {
        const err = await res.json();
        if (window.showToast) window.showToast(err.error || 'Failed to save clinic profile.', 'danger');
      }
    } catch {
      if (window.showToast) window.showToast('Server error. Please try again.', 'danger');
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '200px' }}>
        <div style={{ textAlign: 'center', color: 'var(--text-muted)' }}>
          <div style={{ fontSize: '2rem', marginBottom: '0.5rem' }}>⚙️</div>
          <p>Loading clinic profile...</p>
        </div>
      </div>
    );
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>

      {/* Page Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '1rem' }}>
        <div>
          <h2 style={{ color: 'var(--dark)', fontWeight: 800, marginBottom: '0.25rem' }}>Clinic Profile Settings</h2>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.88rem' }}>
            These details appear on every invoice, receipt, and report generated by the system.
          </p>
        </div>
        <button
          onClick={handleSave}
          disabled={saving}
          className="btn btn-primary"
          style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', padding: '0.65rem 1.5rem', fontWeight: 700 }}
        >
          {saving ? (
            <>⏳ Saving...</>
          ) : saved ? (
            <>✅ Saved!</>
          ) : (
            <>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"/><polyline points="17 21 17 13 7 13 7 21"/><polyline points="7 3 7 8 15 8"/>
              </svg>
              Save Profile
            </>
          )}
        </button>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem' }}>

        {/* ── LEFT: FORM ──────────────────────────────────────────────── */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>

          {/* Basic Info */}
          <div className="card">
            <h3 className="card-title" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>
              Basic Information
            </h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              <div style={{ display: 'flex', gap: '1.5rem', alignItems: 'center', borderBottom: '1px solid var(--border)', paddingBottom: '1.25rem' }}>
                {profile.logo ? (
                  <div style={{ position: 'relative', display: 'inline-block' }}>
                    <img src={profile.logo} alt="Clinic Logo" style={{ width: '80px', height: '80px', objectFit: 'contain', border: '1px solid var(--border)', borderRadius: '8px', padding: '4px', background: '#fff' }} />
                    <button 
                      type="button" 
                      onClick={() => handleChange('logo', '')}
                      style={{ position: 'absolute', top: '-6px', right: '-6px', background: 'var(--danger)', color: '#fff', border: 'none', borderRadius: '50%', width: '20px', height: '20px', fontSize: '0.7rem', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', boxShadow: 'var(--shadow-sm)', fontWeight: 'bold' }}
                      title="Remove Logo"
                    >
                      ✕
                    </button>
                  </div>
                ) : (
                  <div style={{ width: '80px', height: '80px', border: '2px dashed var(--border)', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-muted)', fontSize: '1.6rem', background: '#fafafa' }}>
                    🖼️
                  </div>
                )}
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
                  <span style={{ fontWeight: 600, fontSize: '0.85rem', color: 'var(--dark)' }}>Clinic Logo</span>
                  <input 
                    type="file" 
                    accept="image/*" 
                    onChange={handleLogoUpload} 
                    id="clinic-logo-input" 
                    style={{ display: 'none' }} 
                  />
                  <label 
                    htmlFor="clinic-logo-input" 
                    className="btn btn-secondary" 
                    style={{ padding: '0.4rem 0.85rem', fontSize: '0.78rem', cursor: 'pointer', display: 'inline-block', textAlign: 'center', fontWeight: 600, border: '1px solid var(--border)' }}
                  >
                    Choose Image
                  </label>
                  <span style={{ fontSize: '0.68rem', color: 'var(--text-muted)' }}>PNG, JPG or SVG. Max 500KB.</span>
                </div>
              </div>
              <div className="form-group" style={{ marginBottom: 0 }}>
                <label className="form-label">Clinic / Hospital Name <span style={{ color: 'var(--danger)' }}>*</span></label>
                <input
                  type="text"
                  className="form-input"
                  value={profile.clinic_name}
                  onChange={e => handleChange('clinic_name', e.target.value)}
                  placeholder="e.g. Care & Cure Clinic"
                />
              </div>
              <div className="form-group" style={{ marginBottom: 0 }}>
                <label className="form-label">Tagline / Subtitle</label>
                <input
                  type="text"
                  className="form-input"
                  value={profile.tagline}
                  onChange={e => handleChange('tagline', e.target.value)}
                  placeholder="e.g. Advanced Healthcare & Wellness Centre"
                />
              </div>
              <div className="form-group" style={{ marginBottom: 0 }}>
                <label className="form-label">Registration / License Number</label>
                <input
                  type="text"
                  className="form-input"
                  value={profile.reg_number}
                  onChange={e => handleChange('reg_number', e.target.value)}
                  placeholder="e.g. MOH-LK-00123"
                />
              </div>
            </div>
          </div>

          {/* Contact & Location */}
          <div className="card">
            <h3 className="card-title" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"/><circle cx="12" cy="10" r="3"/></svg>
              Address &amp; Contact
            </h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              <div className="form-group" style={{ marginBottom: 0 }}>
                <label className="form-label">Street Address</label>
                <input
                  type="text"
                  className="form-input"
                  value={profile.address}
                  onChange={e => handleChange('address', e.target.value)}
                  placeholder="e.g. 123 Medical Plaza, Suite 401"
                />
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem' }}>
                <div className="form-group" style={{ marginBottom: 0 }}>
                  <label className="form-label">City</label>
                  <input
                    type="text"
                    className="form-input"
                    value={profile.city}
                    onChange={e => handleChange('city', e.target.value)}
                    placeholder="e.g. Colombo 03"
                  />
                </div>
                <div className="form-group" style={{ marginBottom: 0 }}>
                  <label className="form-label">Country</label>
                  <input
                    type="text"
                    className="form-input"
                    value={profile.country}
                    onChange={e => handleChange('country', e.target.value)}
                    placeholder="e.g. Sri Lanka"
                  />
                </div>
              </div>
              <div className="form-group" style={{ marginBottom: 0 }}>
                <label className="form-label">Phone <span style={{ color: 'var(--danger)' }}>*</span></label>
                <input
                  type="text"
                  className="form-input"
                  value={profile.phone}
                  onChange={e => handleChange('phone', e.target.value)}
                  placeholder="e.g. +94 11 555 7890"
                />
              </div>
              <div className="form-group" style={{ marginBottom: 0 }}>
                <label className="form-label">Email Address</label>
                <input
                  type="email"
                  className="form-input"
                  value={profile.email}
                  onChange={e => handleChange('email', e.target.value)}
                  placeholder="e.g. info@yourclinic.com"
                />
              </div>
              <div className="form-group" style={{ marginBottom: 0 }}>
                <label className="form-label">Website</label>
                <input
                  type="url"
                  className="form-input"
                  value={profile.website}
                  onChange={e => handleChange('website', e.target.value)}
                  placeholder="e.g. https://www.yourclinic.com"
                />
              </div>
            </div>
          </div>

          {/* Invoice Text */}
          <div className="card">
            <h3 className="card-title" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><polyline points="10 9 9 9 8 9"/></svg>
              Invoice Footer Text
            </h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              <div className="form-group" style={{ marginBottom: 0 }}>
                <label className="form-label">Thank You Message</label>
                <input
                  type="text"
                  className="form-input"
                  value={profile.footer_note}
                  onChange={e => handleChange('footer_note', e.target.value)}
                  placeholder="e.g. Thank you for trusting us with your health!"
                />
              </div>
              <div className="form-group" style={{ marginBottom: 0 }}>
                <label className="form-label">Disclaimer Text</label>
                <textarea
                  className="form-input"
                  rows={3}
                  value={profile.disclaimer}
                  onChange={e => handleChange('disclaimer', e.target.value)}
                  placeholder="e.g. This is a computer-generated invoice and does not require a physical signature."
                  style={{ resize: 'vertical' }}
                />
              </div>
            </div>
          </div>
        </div>

        {/* ── RIGHT: LIVE PREVIEW ─────────────────────────────────────── */}
        <div>
          <div className="card" style={{ position: 'sticky', top: '1rem' }}>
            <h3 className="card-title" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1.25rem' }}>
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>
              Invoice Preview
            </h3>
            <p style={{ fontSize: '0.78rem', color: 'var(--text-muted)', marginBottom: '1rem' }}>
              This is exactly how your clinic details will appear on generated invoices.
            </p>

            {/* Invoice Brand Bar Preview */}
            <div style={{
              background: 'linear-gradient(135deg, hsl(172, 66%, 30%) 0%, hsl(172, 66%, 22%) 100%)',
              borderRadius: '8px 8px 0 0', padding: '1rem 1.25rem',
              display: 'flex', justifyContent: 'space-between', alignItems: 'center'
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                {profile.logo ? (
                  <img src={profile.logo} alt="Preview Logo" style={{ width: '36px', height: '36px', objectFit: 'contain', borderRadius: '6px', background: '#fff', padding: '2px' }} />
                ) : (
                  <svg width="36" height="36" viewBox="0 0 42 42" fill="none">
                    <rect width="42" height="42" rx="10" fill="white" fillOpacity="0.18"/>
                    <rect x="17" y="7" width="8" height="28" rx="3" fill="white"/>
                    <rect x="7" y="17" width="28" height="8" rx="3" fill="white"/>
                  </svg>
                )}
                <div>
                  <div style={{ fontWeight: 800, color: 'white', fontSize: '0.95rem' }}>
                    {profile.clinic_name || <span style={{ opacity: 0.5 }}>Clinic Name</span>}
                  </div>
                  <div style={{ fontSize: '0.65rem', color: 'rgba(255,255,255,0.7)', marginTop: '0.1rem' }}>
                    {profile.tagline || <span style={{ opacity: 0.5 }}>Tagline</span>}
                  </div>
                </div>
              </div>
              <div style={{ textAlign: 'right' }}>
                <div style={{ fontSize: '0.6rem', color: 'rgba(255,255,255,0.6)', letterSpacing: '0.1em' }}>INVOICE</div>
                <div style={{ fontSize: '0.8rem', fontWeight: 700, color: 'white', fontFamily: 'monospace' }}>#INV-XXXXX</div>
              </div>
            </div>

            {/* Clinic Info Preview */}
            <div style={{
              border: '1px solid var(--border)', borderTop: 'none',
              borderRadius: '0 0 8px 8px', padding: '1rem 1.25rem',
              display: 'flex', justifyContent: 'space-between', gap: '1rem',
              fontSize: '0.78rem', color: 'var(--text-muted)', background: '#fff'
            }}>
              <div>
                <div style={{ fontWeight: 700, color: 'var(--dark)', marginBottom: '0.25rem' }}>
                  {profile.clinic_name || 'Clinic Name'}
                </div>
                {profile.address && <div>{profile.address}</div>}
                {(profile.city || profile.country) && <div>{[profile.city, profile.country].filter(Boolean).join(', ')}</div>}
                {profile.phone && <div>Tel: {profile.phone}</div>}
                {profile.email && <div>Email: {profile.email}</div>}
                {profile.reg_number && <div style={{ marginTop: '0.3rem', fontSize: '0.7rem', color: 'var(--text-muted)' }}>Reg: {profile.reg_number}</div>}
              </div>
              <div style={{ textAlign: 'right', fontSize: '0.75rem' }}>
                <div style={{ color: 'var(--text-muted)' }}>Invoice No: <strong style={{ color: 'var(--dark)' }}>INV-XXXXX</strong></div>
                <div style={{ color: 'var(--text-muted)', marginTop: '0.2rem' }}>Date: <strong style={{ color: 'var(--dark)' }}>2026-06-23</strong></div>
                <div style={{ color: 'var(--text-muted)', marginTop: '0.2rem' }}>Status: <span style={{ background: '#dcfce7', color: '#16a34a', fontWeight: 700, padding: '0.1rem 0.4rem', borderRadius: '4px', fontSize: '0.68rem' }}>PAID</span></div>
              </div>
            </div>

            {/* Footer Preview */}
            <div style={{
              marginTop: '0.75rem', padding: '0.75rem 1rem',
              background: 'var(--light)', borderRadius: '6px', border: '1px solid var(--border)',
              fontSize: '0.75rem', color: 'var(--text-muted)'
            }}>
              <div style={{ fontWeight: 700, color: 'var(--primary)', marginBottom: '0.2rem' }}>{profile.clinic_name || 'Clinic Name'}</div>
              <div>{[profile.address, profile.city, profile.country].filter(Boolean).join(', ')}</div>
              {profile.phone && <div>Tel: {profile.phone}{profile.email ? ` | ${profile.email}` : ''}</div>}
              {profile.footer_note && <div style={{ marginTop: '0.35rem', fontStyle: 'italic' }}>{profile.footer_note}</div>}
            </div>

            {profile.disclaimer && (
              <div style={{
                marginTop: '0.5rem', padding: '0.5rem 0.75rem',
                background: '#f9fdfb', borderRadius: '6px',
                fontSize: '0.65rem', color: '#9ab5af', textAlign: 'center', border: '1px solid #e8f5f2'
              }}>
                {profile.disclaimer}
              </div>
            )}

            {/* Save reminder */}
            {!saved && (
              <div style={{
                marginTop: '1rem', padding: '0.6rem 0.8rem',
                background: 'var(--warning-light)', border: '1px solid var(--warning)',
                borderRadius: '6px', fontSize: '0.78rem', color: '#92400e',
                display: 'flex', alignItems: 'center', gap: '0.4rem'
              }}>
                ⚠️ Changes are not saved yet. Click <strong>Save Profile</strong> above.
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
